### ISSUE TITLE
Miniconda 'pandas' error

### ISSUE THREAD

**Issue by erenada** [BobLiterman/Rboretum#13]
Code Run:

_library(Rboretum)

source_python(system.file("", "Split_Processor.py", package = "Rboretum"))_

Error: 

_Error in py_run_file_impl(file, local, convert) : 
  ModuleNotFoundError: No module named 'pandas'_

**Comment by erenada** [comment]
Anaconda installation might be needed.

**Comment by BobLiterman** [comment]
Users can use whichever python installation they want, but it's critical that 'reticulate' knows which python  you mean to use. Double check how your reticulate was installed, as it may be pointing  to a system default Python rather than whichever environment you happen to have your packages installed into (e.g. pandas or biopython).

**Comment by BobLiterman** [comment]
Make test script

**Comment by rachelss** [comment]
For installation of packages see #10
